// action type constants

const TYPES = {
  FETCH_QUESTIONS: 'FETCH_QUESTIONS',
  FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
  RESET_QUESTIONS: 'RESET_QUESTIONS',

  FETCH_USER_ANSWERS: 'FETCH_USER_ANSWERS',
  FETCH_USER_ANSWERS_SUCCESS: 'FETCH_USER_ANSWERS_SUCCESS',

  SET_CURRENT_QUESTION_INDEX: 'SET_CURRENT_QUESTION_INDEX',

  STORE_USER_ANSWER: 'STORE_USER_ANSWER', // store in local state
  RESET_USER_ANSWER: 'RESET_USER_ANSWER', // remove from local state
  SET_USER_ANSWER: 'SET_USER_ANSWER', // store in db
  SET_USER_ANSWER_SUCCESS: 'SET_USER_ANSWER_SUCCESS', // update in local state

  CLEAR_USER_ANSWERS: 'CLEAR_USER_ANSWERS',
};

export default TYPES;
